/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BonusRouteImport } from './routes/bonus'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as ProjetoIdRouteImport } from './routes/projeto.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BonusRoute = BonusRouteImport.update({
  id: '/bonus',
  path: '/bonus',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetoIdRoute = ProjetoIdRouteImport.update({
  id: '/projeto/$id',
  path: '/projeto/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bonus': typeof BonusRoute
  '/dashboard': typeof DashboardRoute
  '/favoritos': typeof FavoritosRoute
  '/projetos': typeof ProjetosRoute
  '/suporte': typeof SuporteRoute
  '/projeto/$id': typeof ProjetoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bonus': typeof BonusRoute
  '/dashboard': typeof DashboardRoute
  '/favoritos': typeof FavoritosRoute
  '/projetos': typeof ProjetosRoute
  '/suporte': typeof SuporteRoute
  '/projeto/$id': typeof ProjetoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bonus': typeof BonusRoute
  '/dashboard': typeof DashboardRoute
  '/favoritos': typeof FavoritosRoute
  '/projetos': typeof ProjetosRoute
  '/suporte': typeof SuporteRoute
  '/projeto/$id': typeof ProjetoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bonus'
    | '/dashboard'
    | '/favoritos'
    | '/projetos'
    | '/suporte'
    | '/projeto/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bonus'
    | '/dashboard'
    | '/favoritos'
    | '/projetos'
    | '/suporte'
    | '/projeto/$id'
  id:
    | '__root__'
    | '/'
    | '/bonus'
    | '/dashboard'
    | '/favoritos'
    | '/projetos'
    | '/suporte'
    | '/projeto/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BonusRoute: typeof BonusRoute
  DashboardRoute: typeof DashboardRoute
  FavoritosRoute: typeof FavoritosRoute
  ProjetosRoute: typeof ProjetosRoute
  SuporteRoute: typeof SuporteRoute
  ProjetoIdRoute: typeof ProjetoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bonus': {
      id: '/bonus'
      path: '/bonus'
      fullPath: '/bonus'
      preLoaderRoute: typeof BonusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projeto/$id': {
      id: '/projeto/$id'
      path: '/projeto/$id'
      fullPath: '/projeto/$id'
      preLoaderRoute: typeof ProjetoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BonusRoute: BonusRoute,
  DashboardRoute: DashboardRoute,
  FavoritosRoute: FavoritosRoute,
  ProjetosRoute: ProjetosRoute,
  SuporteRoute: SuporteRoute,
  ProjetoIdRoute: ProjetoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
